/*
 * Copyright (C) 2014 Simon Dahlberg and Jesper Sahlin
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package databasprojektet;

import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.WindowEvent;
import java.awt.event.WindowFocusListener;
import java.awt.event.WindowStateListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author Simon Dahlberg and Jesper Sahlin
 */
public class AdminWindow extends javax.swing.JFrame
{

    private ArrayList<User> mUserList;

    /**
     * Creates new form AdminPanel
     */
    public AdminWindow()
    {
        initComponents();
        InitializeUsers();
        addWindowFocusListener(new WindowFocusListener()
        {

            @Override
            public void windowGainedFocus(WindowEvent e)
            {
                InitializeUsers();
            }

            @Override
            public void windowLostFocus(WindowEvent e)
            {
                //Do nothing
            }
        });


    }

    private void InitializeUsers()
    {
        ResultSet usersFromDb = SQLHelper.GetResultSetFromQuery("SELECT * from users order by UserName");
        mUserList = new ArrayList<User>();
        try
        {
            while (usersFromDb.next())
            {
                mUserList.add(new User(usersFromDb.getInt("ID"), usersFromDb.getString("UserName"), usersFromDb.getString("Password"), usersFromDb.getBoolean("IsAdmin")));
            }

        }
        catch (SQLException e)
        {
            System.out.println(e);
        }
        DefaultListModel<String> listModel = new DefaultListModel<>();
        for (int i = 0; i < mUserList.size(); i++)
        {
            listModel.addElement(mUserList.get(i).GetName());
        }
        jListUsers.setModel(listModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jTabbedPane = new javax.swing.JTabbedPane();
        pnlUser = new javax.swing.JPanel();
        btnNewUser = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListUsers = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtUserInfo = new javax.swing.JTextArea();
        btnRemoveUser = new javax.swing.JButton();
        pnlPun = new javax.swing.JPanel();
        btnNewPun = new javax.swing.JButton();

        setTitle("Administratör");

        btnNewUser.setText("Ny Användare");
        btnNewUser.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnNewUserActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jListUsers);

        txtUserInfo.setColumns(20);
        txtUserInfo.setRows(5);
        jScrollPane2.setViewportView(txtUserInfo);

        btnRemoveUser.setText("Ta bort användare");
        btnRemoveUser.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnRemoveUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlUserLayout = new javax.swing.GroupLayout(pnlUser);
        pnlUser.setLayout(pnlUserLayout);
        pnlUserLayout.setHorizontalGroup(
            pnlUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(pnlUserLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnRemoveUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNewUser))
            .addGroup(pnlUserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        pnlUserLayout.setVerticalGroup(
            pnlUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNewUser)
                    .addComponent(btnRemoveUser)))
        );

        jTabbedPane.addTab("Användare", pnlUser);

        btnNewPun.setText("Nytt Skämt");
        btnNewPun.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnNewPunActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPunLayout = new javax.swing.GroupLayout(pnlPun);
        pnlPun.setLayout(pnlPunLayout);
        pnlPunLayout.setHorizontalGroup(
            pnlPunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPunLayout.createSequentialGroup()
                .addGap(0, 380, Short.MAX_VALUE)
                .addComponent(btnNewPun, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlPunLayout.setVerticalGroup(
            pnlPunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPunLayout.createSequentialGroup()
                .addGap(0, 317, Short.MAX_VALUE)
                .addComponent(btnNewPun))
        );

        jTabbedPane.addTab("Skämt", pnlPun);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewPunActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnNewPunActionPerformed
    {//GEN-HEADEREND:event_btnNewPunActionPerformed
        
    }//GEN-LAST:event_btnNewPunActionPerformed

    private void btnNewUserActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnNewUserActionPerformed
    {//GEN-HEADEREND:event_btnNewUserActionPerformed
        RegistrationWindow r = new RegistrationWindow(true);
        r.setVisible(true);
    }//GEN-LAST:event_btnNewUserActionPerformed

    private void btnRemoveUserActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnRemoveUserActionPerformed
    {//GEN-HEADEREND:event_btnRemoveUserActionPerformed
        String s = jListUsers.getSelectedValue().toString();
        
        boolean deleted = false;
        for (int i = 0; i < mUserList.size(); i++)
        {
            if (mUserList.get(i).GetName().equals(s))
            {
                int id = mUserList.get(i).GetId();
                mUserList.remove(i);
                String removeQuery = "DELETE FROM Users WHERE ID = '" + id + "';";
                SQLHelper.ExecuteUpdate(removeQuery);
                deleted = true;
                break;
            }
        }
        
        if(!deleted)
        {
            System.out.println("User not found and could not be deleted");
        }
        
        InitializeUsers();

    }//GEN-LAST:event_btnRemoveUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(AdminWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(AdminWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(AdminWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(AdminWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new AdminWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNewPun;
    private javax.swing.JButton btnNewUser;
    private javax.swing.JButton btnRemoveUser;
    private javax.swing.JList jListUsers;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JPanel pnlPun;
    private javax.swing.JPanel pnlUser;
    private javax.swing.JTextArea txtUserInfo;
    // End of variables declaration//GEN-END:variables

}
